WIP

diff --git a/docker/nginx/scripts/setup-config b/docker/nginx/scripts/setup-config
--- a/docker/nginx/scripts/setup-config
+++ b/docker/nginx/scripts/setup-config
@@ -4,7 +4,10 @@
 APP_DIR=/var/www/app
 VARIABLES_DIR=/variables
 
-echo "Creating Cherrycake setup configuration files"
+if [ ! -f $APP_DIR/load.php ]; then
+	echo "Cherrycake skeleton is not installed, couldn't create configuration files"
+	exit 1
+fi
 
 # Create database configuration file
 if [ -f $APP_DIR/config/Database.config.php ]; then
diff --git a/docker/nginx/scripts/setup-nginx b/docker/nginx/scripts/setup-nginx
--- a/docker/nginx/scripts/setup-nginx
+++ b/docker/nginx/scripts/setup-nginx
@@ -3,6 +3,11 @@
 
 APP_DIR=/var/www/app
 
+if [ ! -f $APP_DIR/load.php ]; then
+	echo "Cherrycake skeleton is not installed, couldn't setup Nginx"
+	exit 1
+fi
+
 echo "
 	server {
 		listen 80 default_server;
